[config]
schemaVersion = "0.0.1"

[package]
namespace = "Gregorio"
name = "EigongPrime"
versionNumber = "2.3.3"
description = "Mods Eigong to be harder"
websiteUrl = "https://github.com/MicheliniDev/NineSolsEigongPrimeMod"
containsNsfwContent = false

[package.dependencies]
"BepInEx-BepInExPack" = "5.4.2100"
"ninesolsmodding-NineSolsAPI" = "1.2.1"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "build/dll"
target = "."

[publish]
repository = "https://thunderstore.io"
communities = [ "nine-sols" ]
